// Iconfont PNG mapping — use root-absolute paths so cover-image works on 微信小程序
// 态势页图标：文件名与 iconKey 一致，便于从 iconfont 导出 PNG 后直接覆盖 static/icons/
const _BASE = '/static/icons/'

const iconSvgUri = {
  'admin':          _BASE + 'admin.png',
  'add-case':       _BASE + 'add-case.png',
  'all-devices':    _BASE + 'all-devices.png',
  'alert-critical': _BASE + 'alert-critical.png',
  'alert-handled':  _BASE + 'alert-handled.png',
  'alert-warning':  _BASE + 'alert-warning.png',
  'arrow-down':     _BASE + 'arrow-down.png',
  'battery-0':      _BASE + 'battery-0.png',
  'battery-1':      _BASE + 'battery-1.png',
  'battery-2':      _BASE + 'battery-2.png',
  'battery-3':      _BASE + 'battery-3.png',
  'boundary-marker':_BASE + 'boundary-marker.png',
  'camera-infrared':_BASE + 'camera-infrared.png',
  'camera-visible': _BASE + 'camera-visible.png',
  'chart':          _BASE + 'chart.png',
  'checkpoint':     _BASE + 'checkpoint.png',
  'clue-verify':    _BASE + 'clue-verify.png',
  'compass':        _BASE + 'compass.png',
  'default':        _BASE + 'default.png',
  'dispatch':       _BASE + 'dispatch.png',
  'drone':          _BASE + 'drone.png',
  'fiber':          _BASE + 'fiber.png',
  'food':           _BASE + 'food.png',
  'gps':            _BASE + 'gps.png',
  'infrared':       _BASE + 'infrared.png',
  'intel':          _BASE + 'intel.png',
  'layers':         _BASE + 'layers.png',
  'live-transport': _BASE + 'live-transport.png',
  'location':       _BASE + 'location.png',
  'logo':           _BASE + 'logo.png',
  'monitoring':     _BASE + 'monitoring.png',
  'officer':        _BASE + 'officer.png',
  'patrol':         _BASE + 'patrol.png',
  'risk-judge':     _BASE + 'risk-judge.png',
  'risk-profile':   _BASE + 'risk-profile.png',
  'ruler':          _BASE + 'ruler.png',
  'sampling':       _BASE + 'sampling.png',
  'satellite':      _BASE + 'satellite.png',
  'search':         _BASE + 'search.png',
  'sensor':         _BASE + 'sensor.png',
  'sentry':         _BASE + 'sentry.png',
  'shield-gx':      _BASE + 'shield-gx.png',
  'site-verify':    _BASE + 'site-verify.png',
  'sos':            _BASE + 'sos.png',
  'species':        _BASE + 'species.png',
  'storage-box':    _BASE + 'storage-box.png',
  'sync':           _BASE + 'sync.png',
  'terrain':        _BASE + 'terrain.png',
  'trace':          _BASE + 'trace.png',
  'vehicle':        _BASE + 'vehicle.png',
  'vehicle-check':  _BASE + 'vehicle-check.png',
  'vibration':      _BASE + 'vibration.png',
}

export { iconSvgUri }
